import { addScheduledResearch } from "../server/commentators/commentatorService.ts";

const entries = [
  { sectorId: "reserve", sourceTier: "verified_news", sourceUrl: "https://www.fool.com/investing/2026/08/08/the-white-house-continues-to-promote-the-strategic/", sourceTitle: "The White House Continues to Promote the Strategic Bitcoin Reserve", body: "The Motley Fool haberi, Beyaz Saray ve milletvekillerinin Stratejik Bitcoin Rezervi için ARMA gibi yasal adımları ve uzun vadeli kilitlenme mekanizmalarını tartışmayı sürdürdüğünü aktarıyor. Bu, Bitcoinin kurumsal ve egemen entegrasyon yönünü izlemek için önemlidir; sektörün tüm varlıkları için doğrudan sonuç garanti etmez." },
  { sectorId: "infrastructure", sourceTier: "official", sourceUrl: "https://solana.com/news/solana-ecosystem-roundup-july-2026", sourceTitle: "Solana Ecosystem Roundup: July 2026", body: "Solana resmî duyurusu, ağın maksimum blok kapasitesinin Temmuz ayında yüzde 66 artırılarak 100 milyon işlem birimine çıkarıldığını bildiriyor. Bu altyapı kapasitesi ve ölçeklenebilirlik gelişmesi takip edilir; sektörün diğer tüm varlıklarına doğrudan sonuç çıkarılamaz." },
  { sectorId: "frontier", sourceTier: "verified_news", sourceUrl: "https://www.tao.media/zipcode-shifts-subnet-46-to-instant-as-bittensor-rule-changes-raise-pressure-on-builders/", sourceTitle: "Zipcode Shifts Subnet 46 to Instant as Bittensor Rule Changes Raise Pressure on Builders", body: "TAO Media haberi, Bittensor V440 güncellemesindeki Emisyon Kapısı mekanizmasının subnetleri talep odaklı modele yönelttiğini aktarıyor. Ağ ekonomik kurallarının proje stratejilerine etkisi frontier sektörü için izlenir; tüm sektör varlıkları için aynı sonuç geçerli değildir." },
  { sectorId: "liquidity", sourceTier: "verified_news", sourceUrl: "https://www.tradingview.com/news/cointelegraph:01d839542094b:0-rwas-buck-defi-slowdown-as-tokenized-assets-gain-traction-coinshares/", sourceTitle: "RWAs buck DeFi slowdown as tokenized assets gain traction: CoinShares", body: "CoinShares ve Token Terminal verilerine dayanan haber, 2026 ikinci çeyreğinde DeFi üzerindeki RWA mevduatlarının yıllık bazda üç katından fazla artarak 7,4 milyar dolara ulaştığını bildiriyor. RWA ve stablecoin likidite kullanımını izlemek için önemlidir; tüm sektör varlıkları için doğrudan olumlu sonuç değildir." },
  { sectorId: "archive", sourceTier: "official", sourceUrl: "https://www.filecoin.io/blog/Solstice-Towards-a-Filecoin-Service-Economy", sourceTitle: "Solstice: Towards a Filecoin Service Economy", body: "Filecoin topluluğunun Solstice FIP 0118 teklifi, ağ ödül sistemini hizmet ekonomisine dönüştürmeyi ve hizmet sağlayıcılara yönelen teşvikleri değiştirmeyi hedefliyor. Ağ ekonomisi ve depolama teşvikleri için takip edilir; sektörün tüm varlıkları için aynı etkiyi ifade etmez." },
  { sectorId: "commons", sourceTier: "verified_news", sourceUrl: "https://www.blockchaingamer.biz/news/42719/the-sandbox-tweaks-land-functionality-ai-tools-reboot/", sourceTitle: "The Sandbox tweaks LAND benefits as part of AI tools reboot", body: "BlockchainGamer haberi, The Sandboxın yapay zekâ destekli stüdyo araçlarıyla LAND NFT hakları, oyun keşfi ve gelir paylaşımı üzerinde güncellemeler planladığını bildiriyor. GameFi ve topluluk odaklı içerik üretimi için takip edilir; commons sektöründeki tüm varlıklara doğrudan sonuç çıkarılamaz." },
];

const result = await addScheduledResearch(entries);
console.log(JSON.stringify({ entries: entries.length, ...result }, null, 2));
