export type ProvinceId = "reserve" | "infrastructure" | "frontier" | "liquidity" | "archive" | "commons";

export type MarketAssetRecord = {
  reportIndex: number;
  symbol: string;
  name: string;
  provinceId: ProvinceId;
  coinGeckoId: string | null;
  availability: "available" | "unavailable";
  duplicateReportRecord?: boolean;
  note?: string;
};

// Generated from the Gemini report list and verified against CoinGecko's coin list on 2026-08-12.
// This is a market-data mapping only; it never creates an order or handles a real wallet.
export const MARKET_ASSET_MANIFEST: MarketAssetRecord[] = [
  { reportIndex: 1, symbol: "BTC", name: "Bitcoin", provinceId: "reserve", coinGeckoId: "bitcoin", availability: "available" },
  { reportIndex: 2, symbol: "ETH", name: "Ethereum", provinceId: "infrastructure", coinGeckoId: "ethereum", availability: "available" },
  { reportIndex: 3, symbol: "SOL", name: "Solana", provinceId: "infrastructure", coinGeckoId: "solana", availability: "available" },
  { reportIndex: 4, symbol: "BNB", name: "BNB", provinceId: "infrastructure", coinGeckoId: "binancecoin", availability: "available" },
  { reportIndex: 5, symbol: "ADA", name: "Cardano", provinceId: "infrastructure", coinGeckoId: "cardano", availability: "available" },
  { reportIndex: 6, symbol: "AVAX", name: "Avalanche", provinceId: "infrastructure", coinGeckoId: "avalanche-2", availability: "available" },
  { reportIndex: 7, symbol: "DOT", name: "Polkadot", provinceId: "infrastructure", coinGeckoId: "polkadot", availability: "available" },
  { reportIndex: 8, symbol: "MATIC / POL", name: "Polygon", provinceId: "infrastructure", coinGeckoId: "polygon-ecosystem-token", availability: "available" },
  { reportIndex: 9, symbol: "TRX", name: "TRON", provinceId: "infrastructure", coinGeckoId: "tron", availability: "available" },
  { reportIndex: 10, symbol: "LINK", name: "Chainlink", provinceId: "infrastructure", coinGeckoId: "chainlink", availability: "available" },
  { reportIndex: 11, symbol: "TON", name: "Toncoin", provinceId: "infrastructure", coinGeckoId: "the-open-network", availability: "available" },
  { reportIndex: 12, symbol: "NEAR", name: "Near Protocol", provinceId: "infrastructure", coinGeckoId: "near", availability: "available" },
  { reportIndex: 13, symbol: "APT", name: "Aptos", provinceId: "infrastructure", coinGeckoId: "aptos", availability: "available" },
  { reportIndex: 14, symbol: "SUI", name: "Sui", provinceId: "infrastructure", coinGeckoId: "sui", availability: "available" },
  { reportIndex: 15, symbol: "ALGO", name: "Algorand", provinceId: "infrastructure", coinGeckoId: "algorand", availability: "available" },
  { reportIndex: 16, symbol: "ATOM", name: "Cosmos", provinceId: "infrastructure", coinGeckoId: "cosmos", availability: "available" },
  { reportIndex: 17, symbol: "ICP", name: "Internet Computer", provinceId: "infrastructure", coinGeckoId: "internet-computer", availability: "available" },
  { reportIndex: 18, symbol: "HBAR", name: "Hedera", provinceId: "infrastructure", coinGeckoId: "hedera-hashgraph", availability: "available" },
  { reportIndex: 19, symbol: "EGLD", name: "MultiversX", provinceId: "infrastructure", coinGeckoId: "elrond-erd-2", availability: "available" },
  { reportIndex: 20, symbol: "FTM", name: "Fantom", provinceId: "infrastructure", coinGeckoId: "fantom", availability: "available" },
  { reportIndex: 21, symbol: "INJ", name: "Injective", provinceId: "infrastructure", coinGeckoId: "injective-protocol", availability: "available" },
  { reportIndex: 22, symbol: "SEI", name: "Sei", provinceId: "infrastructure", coinGeckoId: "sei-network", availability: "available" },
  { reportIndex: 23, symbol: "OP", name: "Optimism", provinceId: "infrastructure", coinGeckoId: "optimism", availability: "available" },
  { reportIndex: 24, symbol: "ARB", name: "Arbitrum", provinceId: "infrastructure", coinGeckoId: "arbitrum", availability: "available" },
  { reportIndex: 25, symbol: "IMX", name: "Immutable X", provinceId: "infrastructure", coinGeckoId: "immutable-x", availability: "available" },
  { reportIndex: 26, symbol: "KAS", name: "Kaspa", provinceId: "infrastructure", coinGeckoId: "kaspa", availability: "available" },
  { reportIndex: 27, symbol: "STX", name: "Stacks", provinceId: "infrastructure", coinGeckoId: "blockstack", availability: "available" },
  { reportIndex: 28, symbol: "TIA", name: "Celestia", provinceId: "infrastructure", coinGeckoId: "celestia", availability: "available" },
  { reportIndex: 29, symbol: "MINA", name: "Mina Protocol", provinceId: "infrastructure", coinGeckoId: "mina-protocol", availability: "available" },
  { reportIndex: 30, symbol: "SANG", name: "Sango Coin", provinceId: "infrastructure", coinGeckoId: null, availability: "unavailable", note: "CoinGecko güncel listesinde Sango Coin doğrulanamadı; yanlış sembol eşleşmesi yapılmadı." },
  { reportIndex: 31, symbol: "CRO", name: "Cronos", provinceId: "infrastructure", coinGeckoId: "crypto-com-chain", availability: "available" },
  { reportIndex: 32, symbol: "VET", name: "VeChain", provinceId: "infrastructure", coinGeckoId: "vechain", availability: "available" },
  { reportIndex: 33, symbol: "XLM", name: "Stellar", provinceId: "infrastructure", coinGeckoId: "stellar", availability: "available" },
  { reportIndex: 34, symbol: "ASTR", name: "Astar", provinceId: "infrastructure", coinGeckoId: "astar", availability: "available" },
  { reportIndex: 35, symbol: "KAVA", name: "Kava", provinceId: "infrastructure", coinGeckoId: "kava", availability: "available" },
  { reportIndex: 36, symbol: "FET", name: "Artificial Superintelligence Alliance / Fetch.ai", provinceId: "frontier", coinGeckoId: "fetch-ai", availability: "available" },
  { reportIndex: 37, symbol: "RNDR / RENDER", name: "Render Network", provinceId: "frontier", coinGeckoId: "render-token", availability: "available" },
  { reportIndex: 38, symbol: "TAO", name: "Bittensor", provinceId: "frontier", coinGeckoId: "bittensor", availability: "available" },
  { reportIndex: 39, symbol: "GRT", name: "The Graph", provinceId: "frontier", coinGeckoId: "the-graph", availability: "available" },
  { reportIndex: 40, symbol: "AGIX", name: "SingularityNET", provinceId: "frontier", coinGeckoId: "singularitynet", availability: "available" },
  { reportIndex: 41, symbol: "OCEAN", name: "Ocean Protocol", provinceId: "frontier", coinGeckoId: "ocean-protocol", availability: "available" },
  { reportIndex: 42, symbol: "AKT", name: "Akash Network", provinceId: "frontier", coinGeckoId: "akash-network", availability: "available" },
  { reportIndex: 43, symbol: "WLD", name: "Worldcoin", provinceId: "frontier", coinGeckoId: "worldcoin-wld", availability: "available" },
  { reportIndex: 44, symbol: "ARKM", name: "Arkham", provinceId: "frontier", coinGeckoId: "arkham", availability: "available" },
  { reportIndex: 45, symbol: "THETA", name: "Theta Network", provinceId: "frontier", coinGeckoId: "theta-token", availability: "available" },
  { reportIndex: 46, symbol: "GLM", name: "Golem", provinceId: "frontier", coinGeckoId: "golem", availability: "available" },
  { reportIndex: 47, symbol: "AIOZ", name: "AIOZ Network", provinceId: "frontier", coinGeckoId: "aioz-network", availability: "available" },
  { reportIndex: 48, symbol: "PRIME", name: "Echelon Prime", provinceId: "frontier", coinGeckoId: "echelon-prime", availability: "available" },
  { reportIndex: 49, symbol: "NFP", name: "NFPrompt", provinceId: "frontier", coinGeckoId: "nfprompt-token", availability: "available" },
  { reportIndex: 50, symbol: "AI", name: "Sleepless AI", provinceId: "frontier", coinGeckoId: "sleepless-ai", availability: "available" },
  { reportIndex: 51, symbol: "XRP", name: "Ripple", provinceId: "liquidity", coinGeckoId: "ripple", availability: "available" },
  { reportIndex: 52, symbol: "LTC", name: "Litecoin", provinceId: "liquidity", coinGeckoId: "litecoin", availability: "available" },
  { reportIndex: 53, symbol: "BCH", name: "Bitcoin Cash", provinceId: "liquidity", coinGeckoId: "bitcoin-cash", availability: "available" },
  { reportIndex: 54, symbol: "MKR", name: "Maker", provinceId: "liquidity", coinGeckoId: "maker", availability: "available" },
  { reportIndex: 55, symbol: "LINK", name: "Chainlink", provinceId: "liquidity", coinGeckoId: "chainlink", availability: "available", duplicateReportRecord: true },
  { reportIndex: 56, symbol: "ONDO", name: "Ondo Finance", provinceId: "liquidity", coinGeckoId: "ondo-finance", availability: "available" },
  { reportIndex: 57, symbol: "PENDLE", name: "Pendle", provinceId: "liquidity", coinGeckoId: "pendle", availability: "available" },
  { reportIndex: 58, symbol: "OM", name: "MANTRA", provinceId: "liquidity", coinGeckoId: "mantra", availability: "available" },
  { reportIndex: 59, symbol: "AAVE", name: "Aave", provinceId: "liquidity", coinGeckoId: "aave", availability: "available" },
  { reportIndex: 60, symbol: "UNI", name: "Uniswap", provinceId: "liquidity", coinGeckoId: "uniswap", availability: "available" },
  { reportIndex: 61, symbol: "COMP", name: "Compound", provinceId: "liquidity", coinGeckoId: "compound-governance-token", availability: "available" },
  { reportIndex: 62, symbol: "CRV", name: "Curve DAO", provinceId: "liquidity", coinGeckoId: "curve-dao-token", availability: "available" },
  { reportIndex: 63, symbol: "FXS", name: "Frax Share", provinceId: "liquidity", coinGeckoId: "frax-share", availability: "available" },
  { reportIndex: 64, symbol: "RBN", name: "Ribbon Finance", provinceId: "liquidity", coinGeckoId: "ribbon-finance", availability: "available" },
  { reportIndex: 65, symbol: "SNX", name: "Synthetix", provinceId: "liquidity", coinGeckoId: "havven", availability: "available" },
  { reportIndex: 66, symbol: "JUP", name: "Jupiter", provinceId: "liquidity", coinGeckoId: "jupiter-exchange-solana", availability: "available" },
  { reportIndex: 67, symbol: "RAY", name: "Raydium", provinceId: "liquidity", coinGeckoId: "raydium", availability: "available" },
  { reportIndex: 68, symbol: "LDO", name: "Lido DAO", provinceId: "liquidity", coinGeckoId: "lido-dao", availability: "available" },
  { reportIndex: 69, symbol: "ENA", name: "Ethena", provinceId: "liquidity", coinGeckoId: "ethena", availability: "available" },
  { reportIndex: 70, symbol: "RPL", name: "Rocket Pool", provinceId: "liquidity", coinGeckoId: "rocket-pool", availability: "available" },
  { reportIndex: 71, symbol: "FIL", name: "Filecoin", provinceId: "archive", coinGeckoId: "filecoin", availability: "available" },
  { reportIndex: 72, symbol: "AR", name: "Arweave", provinceId: "archive", coinGeckoId: "arweave", availability: "available" },
  { reportIndex: 73, symbol: "STORJ", name: "Storj", provinceId: "archive", coinGeckoId: "storj", availability: "available" },
  { reportIndex: 74, symbol: "XMR", name: "Monero", provinceId: "archive", coinGeckoId: "monero", availability: "available" },
  { reportIndex: 75, symbol: "ZEC", name: "Zcash", provinceId: "archive", coinGeckoId: "zcash", availability: "available" },
  { reportIndex: 76, symbol: "DASH", name: "Dash", provinceId: "archive", coinGeckoId: "dash", availability: "available" },
  { reportIndex: 77, symbol: "ENS", name: "Ethereum Name Service", provinceId: "archive", coinGeckoId: "ethereum-name-service", availability: "available" },
  { reportIndex: 78, symbol: "JASMY", name: "JasmyCoin", provinceId: "archive", coinGeckoId: "jasmycoin", availability: "available" },
  { reportIndex: 79, symbol: "SC", name: "Siacoin", provinceId: "archive", coinGeckoId: "siacoin", availability: "available" },
  { reportIndex: 80, symbol: "ANKR", name: "Ankr", provinceId: "archive", coinGeckoId: "ankr", availability: "available" },
  { reportIndex: 81, symbol: "HOT", name: "Holo", provinceId: "archive", coinGeckoId: "holotoken", availability: "available" },
  { reportIndex: 82, symbol: "BAT", name: "Basic Attention Token", provinceId: "archive", coinGeckoId: "basic-attention-token", availability: "available" },
  { reportIndex: 83, symbol: "MASK", name: "Mask Network", provinceId: "archive", coinGeckoId: "mask-network", availability: "available" },
  { reportIndex: 84, symbol: "WMT", name: "World Mobile Token", provinceId: "archive", coinGeckoId: "world-mobile-token", availability: "available" },
  { reportIndex: 85, symbol: "BTT", name: "BitTorrent", provinceId: "archive", coinGeckoId: "bittorrent", availability: "available" },
  { reportIndex: 86, symbol: "DOGE", name: "Dogecoin", provinceId: "commons", coinGeckoId: "dogecoin", availability: "available" },
  { reportIndex: 87, symbol: "SHIB", name: "Shiba Inu", provinceId: "commons", coinGeckoId: "shiba-inu", availability: "available" },
  { reportIndex: 88, symbol: "SAND", name: "The Sandbox", provinceId: "commons", coinGeckoId: "the-sandbox", availability: "available" },
  { reportIndex: 89, symbol: "MANA", name: "Decentraland", provinceId: "commons", coinGeckoId: "decentraland", availability: "available" },
  { reportIndex: 90, symbol: "GALA", name: "Gala Games", provinceId: "commons", coinGeckoId: "gala", availability: "available" },
  { reportIndex: 91, symbol: "AXS", name: "Axie Infinity", provinceId: "commons", coinGeckoId: "axie-infinity", availability: "available" },
  { reportIndex: 92, symbol: "CHZ", name: "Chiliz", provinceId: "commons", coinGeckoId: "chiliz", availability: "available" },
  { reportIndex: 93, symbol: "APE", name: "ApeCoin", provinceId: "commons", coinGeckoId: "apecoin", availability: "available" },
  { reportIndex: 94, symbol: "BEAM", name: "Beam", provinceId: "commons", coinGeckoId: "beam-2", availability: "available" },
  { reportIndex: 95, symbol: "RON", name: "Ronin", provinceId: "commons", coinGeckoId: "ronin", availability: "available" },
  { reportIndex: 96, symbol: "FLOKI", name: "Floki", provinceId: "commons", coinGeckoId: "floki", availability: "available" },
  { reportIndex: 97, symbol: "FLOW", name: "Flow", provinceId: "commons", coinGeckoId: "flow", availability: "available" },
  { reportIndex: 98, symbol: "SUPER", name: "SuperVerse", provinceId: "commons", coinGeckoId: "superfarm", availability: "available" },
  { reportIndex: 99, symbol: "GMT", name: "STEPN", provinceId: "commons", coinGeckoId: "stepn", availability: "available" },
  { reportIndex: 100, symbol: "ENJ", name: "Enjin Coin", provinceId: "commons", coinGeckoId: "enjincoin", availability: "available" },
];

export const SUPPORTED_MARKET_ASSETS = MARKET_ASSET_MANIFEST.filter((asset) => asset.availability === "available" && asset.coinGeckoId);
export const UNAVAILABLE_MARKET_ASSETS = MARKET_ASSET_MANIFEST.filter((asset) => asset.availability === "unavailable");
export const UNIQUE_COIN_GECKO_IDS = Array.from(new Set(SUPPORTED_MARKET_ASSETS.map((asset) => asset.coinGeckoId).filter((id): id is string => Boolean(id))));
